config/routes.rb
Racearama::Application.routes.draw do

  resources :tracks

  resource :race do
    resources :heat_groups do
      resources :heats do
      end
    end
  end
  match 'heats/:heat_id/remove_scout/:scout_id' => 'heats#remove_scout', :as => 'heat_remove_scout'
  match 'heats/:heat_id/add_scout/:scout_id' => 'heats#add_scout', :as => 'heat_add_scout'

  resources :heats do
    resources :races do
      collection do
        delete 'destroy_races'
      end
    end
    member do
      get 'race'
    end
  end
  resources :races do
    member do
      post "stage"
      post "complete"
      post "run"
    end
  end

  resources :settings

  get 'parent' => 'parent#index'
  get 'track_manager' => 'track_manager#index'
  get 'staging' => 'staging#index'
  get 'check_in' => 'check_in#index'
  get 'check_in/new'
  get "page/welcome"
  get "page/event_not_set"

  resources :scouts do
    member do
      get 'check_in'
      get 'check_out'
    end
  end

  resources :dens
  resources :packs

  resources :events do
    member do
      get "set_active"
    end
  end

  devise_for :users, controllers: { sessions: "users/sessions"}

  get 'track_test' => "track_test#index"
  get 'track_test/gate_up' => "track_test#gate_up"
  get 'track_test/gate_down' => "track_test#gate_down"
  get 'track_test/test_race' => "track_test#test_race"
  get 'track_test/test_lanes' => "track_test#test_lanes"
  put 'track_test/set_current_track' => "track_test#set_current_track"
  get "page/copyright"
  get "page/about"

  root :to => "page#welcome"

end

app/models/race.rb
class Race < ActiveRecord::Base
  belongs_to :heat
  has_many :lane_assignments, dependent: :destroy
  has_many :race_times, dependent: :destroy

  attr_accessible :heat_id, :order_index, :daq_seconds

  before_save :only_one_current

  scope :by_index, order("order_index ASC")
  default_scope order("order_index ASC")

  scope :current, where(current: true)
  scope :not_current, where(current: false)
  scope :completed, where(completed: true)
  scope :not_completed, where(completed: false)

  def self.current_race
    Race.current.first
  end

  def self.clear_current
    Race.update_all({current: false}, {current: true})
  end

  private
  def only_one_current
    if (self.new_record? && self.current && Race.current.exists?) ||
       (self.current && Race.current.exists? && (Race.current_race.try(:id) != self.id))
      raise ActiveRecord::ActiveRecordError, "Can not save, another current record exists."
    end
  end
end

app/controllers/race_controller.rb
class RaceController < ApplicationController
  before_filter :current_event
  
  def heat_group
    @heat_group = HeatGroup.new
    @heat_groups = @event.heat_groups
  end
  
  def heat_group_create
    @heat_group = HeatGroup.new(params[:heat_group])

    if @heat_group.save
      redirect_to(race_heat_group_path, :notice => 'Heat group was successfully created.')
    else
      render :action => "new"
    end
    
  end

  def heat
  end

  def assign_lanes
  end

  def do_race
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  # before_filter :current_event
  # before_filter :get_settings
  # before_filter :get_controller_status, only: [:index, :create]
  layout 'layouts/application_bootstrap'

  def index
    @heat = Heat.find(params[:heat_id])
    @heat_group = @heat.heat_group
    @races = @heat.races
  end

  # def show
  #   @race = Race.find(params[:id])
  # end

  # def new
  #   @race = Race.new
  # end

  # def edit
  #   @race = Race.find(params[:id])
  # end

  def create
    @heat = Heat.find(params[:heat_id])
    @heat.generate_races(params[:races_to_generate], params[:selected_lanes])

    @heat.update_attributes({races_to_generate: params[:races_to_generate], generate_method: params[:generate_method], generate_time: Time.now })
    # @lane_to_race = params[:selected_lanes]

    redirect_to heat_races_path
  end

  # def update
  #   @race = Race.find(params[:id])
  #
  #   if @race.update_attributes(params[:race])
  #     redirect_to(@race, notice: 'Race was successfully updated.')
  #   else
  #     render action: "edit"
  #   end
  # end

  # def destroy
  #   @race = Race.find(params[:id])
  #   @race.destroy
  #   redirect_to(races_url)
  # end


  def run
    @race = Race.find(params[:id])
    @race_results = RaceCom.do_race(@race_duration.to_i)
    pp @race_results
    if @race_results[:error]
      flash[:error] = "ERROR! #{@race_results[:error]}"
    elsif @race_results[:result]['status'] == "ok"
      @race_results[:result]['results'].each do |r|
        rt = RaceTime.new({lane: r['lane'], elapsed_seconds: r['time']/1000.0})
        @race.race_times << rt
      end
      @race.update_attributes({completed: true, daq_seconds: @race_results[:elapsed]})
    else
      flash[:error] = "The race controller did not return an OK status."
    end
    render :do_race
  end


  def destroy_races
    @heat = Heat.find(params[:heat_id])
    @heat.races.each{ |race| race.destroy }
    redirect_to heat_races_path
  end


  def stage
    if request.post?
      @race = Race.find(params[:id])
      @race.update_attribute(:current, true)
      redirect_to params[:redirect_to]
    end
  end


  def complete
    if request.post?
      @race = Race.find(params[:id])
      @race.update_attribute(:completed, true)
      redirect_to params[:redirect_to]
    end
  end



  private
  # def run_race(duration)
  #   @return = DaqController.send("start_race".to_sym, @setting.opts, duration)
  #   @race_results = @return[:result]#[:results]
  # end
  #
  #
  # def get_settings
  #   @setting = Setting.first
  #   @race_duration = params["slider-amount"] || "10"
  # end
  #
  #
  # def get_controller_status
  #   @daq_status = DaqController.status(@setting.opts)
  #   if @daq_status.has_key?(:error)
  #     flash[:error] = "Can not communicate with DAQ Controller service (#{@daq_status[:error]}). Verify that the DAQ Controller host/port/api_key are set properly!"
  #   end
  # end
end

app/helpers/race_helper.rb
module RaceHelper
end

app/helpers/races_helper.rb
module RacesHelper
  def active_lane?(lane)
    @active_lanes.include?(lane.to_s)
  end
  
  def lane_color(lane)
    active_lane?(lane) ? "green" : "red"
  end
  
  def race_class(race)
    if race.current
      "current"
    elsif race.completed
      "completed"
    else
      ""
    end
  end
  
  def race_title(race)
    "Race ##{race.order_index} - #{race_class(race).titleize}"
  end
end

app/views/races/_form.html.haml
= form_for @race do |f|
  -if @race.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@race.errors.count, "error")} prohibited this race from being saved:"
      %ul
        - @race.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :line_number
    = f.text_field :line_number
  .field
    = f.label :lane_id
    = f.text_field :lane_id
  .field
    = f.label :elapsed_seconds
    = f.text_field :elapsed_seconds
  .actions
    = f.submit 'Save'

app/views/races/_heat_race_list.html.haml
- heat.races.each_with_index do |race, idx|
  .race-table{class: cycle("mid", "mid", "last")}
    .well.span3.offset1
      %table{class: race_class(race)}
        %thead
          %tr
            %th{colspan: 2, class: 'centered'}= race_title(race)
          %tr
            %th Lane
            %th Scout
        %tbody
          - race.lane_assignments.order("lane ASC").each do |lane_asgn|
            %tr
              %td #{lane_asgn.lane}
              %td #{lane_asgn.scout.full_name}

app/views/races/_lanes.html.haml
- total_lanes = @event.track.total_lanes
- @active_lanes = @event.track.active_lanes.split(",")

%table.table.table-race-lanes
  %thead
    %tr
      %th{colspan: "#{total_lanes}"}= "#{@event.track.pack.name} #{@event.track.name} - Available Lanes"
    %tr
    - total_lanes.times do |n|
      %th{class: lane_color(n+1)}= "#{n+1}"
  %tbody
    %tr
      - total_lanes.times do |n|
        %td= check_box_tag 'selected_lanes[]', n+1, active_lane?(n+1), disabled: !active_lane?(n+1)

app/views/races/_race_generate.html.haml
.centered
  %p.xlarge There are no races generated for this heat. <br/>Generate some!
  = form_tag heat_races_path(@heat.id), class: 'form-inline' do
    = hidden_field_tag 'heat_id', @heat.id
    = hidden_field_tag 'generate_method', "rotation"
    = label_tag 'races_to_generate', 'Races to Generate'
    = text_field_tag :races_to_generate, "4", class: 'span2'
    %br
    = render 'lanes'
    %br
    %p= submit_tag 'Generate Race Schedule', class: 'btn btn-primary'

app/views/races/do_race.html.haml
%h1 Race#do_race
%p Find me in app/views/races/do_race.html.haml

%p= pp @race_results

app/views/races/edit.html.haml
%h1 Editing race

= render 'form'

= link_to 'Show', @race
\|
= link_to 'Back', races_path

app/views/races/index.html.haml
.row-fluid
  .span12
    .page-header
      .pull-right
        = link_to 'Track Management', track_manager_path, class: "btn"
        = link_to "Back to Heat Groups", race_heat_groups_path, class: 'btn'
        = link_to "Back to #{@heat_group.name}-#{@heat.name} Heat", edit_race_heat_group_heat_path(@heat_group, @heat), class: 'btn btn-primary'

      %h2= "Step 4: Create races for #{@heat_group.name}-#{@heat.name} heat"

.row-fluid
  .span10.offset1
    %p.xxlarge Specify the number of races you want to run for this heat. The lane assignment and rotation will automatically be calculated.
    .alert.alert-error
      %h4 IMPORTANT:
      You can not modify or delete any races that have been partially run. Create a new heat, add scouts to that heat, then generate a new race schedule.

    = render 'layouts/event_heat_group'
    %br

    .row-fluid
      .span5
        - if !enough_lanes?
          %p.xlarge There are more scouts than active lanes on the #{@event.track.name} track. You will need to #{link_to "remove some scouts", edit_race_heat_group_heat_path(@heat_group, @heat)} before you can generate races.

        - elsif @heat.races.size > 0
          %strong.xlarge All the races have been generated for this heat.

          - if @heat.has_completed_races? || @heat.has_current_race?
            .alert.alert-block One or more of the races has already completed, or one races is now the current races (probably in staging right now), you may not delete or change any race.

          - else
            .alert.alert-info.alert-block Because none of these races is the current race, and none have been run, you may delete all the races so they can be re-generated.
            %p= link_to "Delete all races", destroy_races_heat_races_path(@heat), method: :delete, class: "btn btn-danger"

        - if @heat.races.size == 0
          .well
            %h4= "Scouts to race in #{@heat_group.name}-#{@heat.name} heat"
            - @heat.scouts.each do |scout|
              %p= scout.full_name
            %p= link_to "Add or edit scouts in #{@heat.name} heat", edit_race_heat_group_heat_path(@heat_group, @heat)

      .span6.offset1
        - if @heat.races.size == 0
          = render 'race_generate'


    - if @heat.races.size > 0
      #race-list
        %h4= "Races generated for the #{@heat.name} heat"
        = render 'heat_race_list', heat: @heat

app/views/races/new.html.haml
%h1 New race

= render 'form'

= link_to 'Back', races_path

app/views/races/show.html.haml
%p
  %b Line number:
  = @race.line_number
%p
  %b Lane:
  = @race.lane_id
%p
  %b Elapsed seconds:
  = @race.elapsed_seconds

= link_to 'Edit', edit_race_path(@race)
\|
= link_to 'Back', races_path