config/routes.rb
Racearama::Application.routes.draw do

  resources :tracks

  resource :race do
    resources :heat_groups do
      resources :heats do
      end
    end
  end
  match 'heats/:heat_id/remove_scout/:scout_id' => 'heats#remove_scout', :as => 'heat_remove_scout'
  match 'heats/:heat_id/add_scout/:scout_id' => 'heats#add_scout', :as => 'heat_add_scout'

  resources :heats do
    resources :races do
      collection do
        delete 'destroy_races'
      end
    end
    member do
      get 'race'
    end
  end
  resources :races do
    member do
      post "stage"
      post "complete"
      post "run"
    end
  end

  resources :settings

  get 'parent' => 'parent#index'
  get 'track_manager' => 'track_manager#index'
  get 'staging' => 'staging#index'
  get 'check_in' => 'check_in#index'
  get 'check_in/new'
  get "page/welcome"
  get "page/event_not_set"

  resources :scouts do
    member do
      get 'check_in'
      get 'check_out'
    end
  end

  resources :dens
  resources :packs

  resources :events do
    member do
      get "set_active"
    end
  end

  devise_for :users, controllers: { sessions: "users/sessions"}

  get 'track_test' => "track_test#index"
  get 'track_test/gate_up' => "track_test#gate_up"
  get 'track_test/gate_down' => "track_test#gate_down"
  get 'track_test/test_race' => "track_test#test_race"
  get 'track_test/test_lanes' => "track_test#test_lanes"
  put 'track_test/set_current_track' => "track_test#set_current_track"
  get "page/copyright"
  get "page/about"

  root :to => "page#welcome"

end

app/controllers/track_manager_controller.rb
class TrackManagerController < ApplicationController
  before_filter :store_params_and_authenticate
  # skip_before_filter :check_for_current_event, :only => [:index]
  layout 'layouts/application_bootstrap'

  def index
    session[:username] = nil
    @ready_to_race = Heat.ready_to_race(@event)
  end

  private
  def store_params_and_authenticate
    session[:username] = "track_manager" unless user_signed_in?
    authenticate_user!
  end

end

app/helpers/track_manager_helper.rb
module TrackManagerHelper
  def current_event_set_icon
    if @event
      image_tag "ok.png"
    else
      image_tag "error.png"
    end
  end
  
  def track_set_icon
    if @event.track
      image_tag "ok.png"
    else
      image_tag "error.png"
    end
  end
  
end

app/views/track_manager/index.html.haml
.page-header
  %h2 Track Management


.row-fluid
  .span5.offset1
    .well
      %h3 Prepare a Race
      = link_to "Create Heats and Races", race_heat_groups_path, class: "btn btn-xlarge btn-block btn-primary"
      / .help-block.centered gentlemen, start your engines

    .well
      %h3 Testing
      = link_to "Track Test", track_test_path, class: "btn btn-xlarge btn-block btn-primary"
      .help-block.centered perform gate and timer tests

    .well
      %h3 Management
      = link_to "Packs", packs_path, class: "btn btn-xlarge btn-block btn-primary"
      .help-block.centered packs have Dens and Tracks
      %br
      = link_to "Dens", dens_path, class: "btn btn-xlarge btn-block btn-primary"
      .help-block.centered dens have Scouts
      %br
      = link_to "Tracks", tracks_path, class: "btn btn-xlarge btn-block btn-primary"
      .help-block.centered tracks belong to a pack, each event has a track
      %br
      = link_to "Scouts", scouts_path, class: "btn btn-xlarge btn-block btn-primary"
      .help-block.centered scouts belong to a den
      %br
      = link_to "Events", events_path, class: "btn btn-xlarge btn-block btn-primary"
      .help-block.centered set events and the current race



  .span5.offset1
    %h2 Race Day Checklist
    %h3 Current Event
    %p= @event.name
    = current_event_set_icon

    %h3 Racing on Track
    %p= @event.track.name_lanes
    = track_set_icon

    %h3 Heats Ready to Race
    - @ready_to_race.each do |heat|
      %ul
        %li
          %h3= link_to "Race #{heat.heat_group.name}-#{heat.name}!", race_heat_path(heat)