config/routes.rb
Racearama::Application.routes.draw do

  resources :tracks

  resource :race do
    resources :heat_groups do
      resources :heats do
      end
    end
  end
  match 'heats/:heat_id/remove_scout/:scout_id' => 'heats#remove_scout', :as => 'heat_remove_scout'
  match 'heats/:heat_id/add_scout/:scout_id' => 'heats#add_scout', :as => 'heat_add_scout'

  resources :heats do
    resources :races do
      collection do
        delete 'destroy_races'
      end
    end
    member do
      get 'race'
    end
  end
  resources :races do
    member do
      post "stage"
      post "complete"
      post "run"
    end
  end

  resources :settings

  get 'parent' => 'parent#index'
  get 'track_manager' => 'track_manager#index'
  get 'staging' => 'staging#index'
  get 'check_in' => 'check_in#index'
  get 'check_in/new'
  get "page/welcome"
  get "page/event_not_set"

  resources :scouts do
    member do
      get 'check_in'
      get 'check_out'
    end
  end

  resources :dens
  resources :packs

  resources :events do
    member do
      get "set_active"
    end
  end

  devise_for :users, controllers: { sessions: "users/sessions"}

  get 'track_test' => "track_test#index"
  get 'track_test/gate_up' => "track_test#gate_up"
  get 'track_test/gate_down' => "track_test#gate_down"
  get 'track_test/test_race' => "track_test#test_race"
  get 'track_test/test_lanes' => "track_test#test_lanes"
  put 'track_test/set_current_track' => "track_test#set_current_track"
  get "page/copyright"
  get "page/about"

  root :to => "page#welcome"

end

app/models/den.rb
class Den < ActiveRecord::Base
  attr_accessible :pack_id, :den_number, :rank, :leader_name, :leader_email, :assistant_leader_name, :assistant_leader_email

  belongs_to :pack
  has_many :scouts

  scope :sort_den, order("den_number ASC")

  validates_uniqueness_of :den_number, :on => :create, :message => "there is another den with this number"

  def name
    "Den #{self.den_number}"
  end

  def den_leader_pack
    "Den #{self.den_number} #{self.rank}, #{self.leader_name} - #{self.pack.name}"
  end

  def has_associated?
    self.scouts.count > 0
  end
end

app/models/scout.rb
class Scout < ActiveRecord::Base
  attr_accessible :den_id, :first_name, :last_name, :address1, :address2, :city, :state, :zipcode, :parent_email1, :parent_email2, :picture

  validates_presence_of :first_name, :last_name
  validates_presence_of :den_id, :message => "must select a den"

  belongs_to :den
  has_and_belongs_to_many :events
  has_and_belongs_to_many :heats, :uniq => true

  has_attached_file :picture, :styles => {:thumb => "100x100>"}, :default_url => "missing.png"

  default_scope includes(:den => :pack)
  scope :not_checked_in, where(:checked_in => false)
  scope :checked_in, where(:checked_in => true)
  scope :sort_fl_name, order("first_name ASC, last_name ASC")
  scope :sort_lf_name, order("last_name ASC, first_name ASC")
  scope :name_or_den_contains,
          lambda {|n|
            joins(:den)
            .where("first_name LIKE ? OR last_name LIKE ? OR dens.den_number = ? OR dens.leader_name LIKE ?",
             "%#{n}%", "%#{n}%", n, "%#{n}%")}
  scope :den_contains, lambda { |n| joins(:den).where("dens.den_number = '#{n}' OR dens.leader_name LIKE '%#{n}%'") }

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def self.number_checked_in
    Scout.checked_in.count
  end

  def self.search_names(name, event=nil)
    if event
      event.scouts.name_or_den_contains(name).sort_fl_name
      # Scout.name_or_den_contains(name).joins(:events).where(event: {id: event.id}).sort_fl_name
    else
      Scout.name_or_den_contains(name).sort_fl_name
    end
  end

  def in_another_heat?(event)
    heat_groups = event.heat_groups
    heat_groups.each do |heat_group|
      heats = heat_group.heats
      heats.each do |heat|
        return true if heat.scouts.exists?(self)
      end
    end
    return false
  end

  def heats_in_event(event)
    self.heats.joins(heat_group: :event).where(events: {id: event.id})
  end

  def has_event?(event)
    self.events.where( :id => event.id ).count > 0
  end

  def has_current_event?
    current_event = Event.current_event
    if current_event
      self.events.where( :id => current_event.id ).count > 0
    else
      return false
    end
  end


end

app/controllers/scouts_controller.rb
class ScoutsController < ApplicationController
  before_filter :authenticate_user!
  # before_filter :current_event
  authorize_resource
  respond_to :html, :rjs
  layout 'layouts/application_bootstrap'

  def index
    @mode = params[:mode] || ""
    @heat_id = params[:heat_id] || ""
    @heat = Heat.find_by_id(@heat_id)
    # @event_id = params[:event_id] || ""
    @event = @heat.heat_group.event if @heat

    if params[:scout_search] || params[:mode]
      @scouts = Scout.search_names(params[:scout_search], @event) #.includes(:den)
    else
      @scouts = Scout.sort_fl_name
    end

    if @mode == "heats" && @heat
      @scouts = @scouts - @heat.scouts
    end
  end


  def show
    @scout = Scout.find(params[:id])
    @current_event = Event.current_event
  end


  def new
    @scout = Scout.new
  end


  def create
    @scout = Scout.new(params[:scout])
    if @scout.save
      flash[:notice] = "Successfully created scout."
      redirect_to scouts_url
    else
      render :new
    end
  end


  def edit
    @scout = Scout.find(params[:id])
    render :edit
  end


  def update
    @scout = Scout.find(params[:id])
    if @scout.update_attributes(params[:scout])
      flash[:notice] = "Successfully updated scout."
      redirect_to scouts_url
    else
      render :edit
    end
  end


  def destroy
    @scout = Scout.find(params[:id])
    @scout.destroy
    flash[:notice] = "Successfully destroyed scout."
    redirect_to scouts_url
  end


  def check_in
    # @event = Event.current_event
    @scout = Scout.find(params[:id])
    # @scout.update_attribute(:checked_in, true)
    @scout.events << @event
    flash[:notice] = "#{@scout.full_name} was sucessfully checked in.<br />If you made a mistake, you can <a href=\"/scouts/#{@scout.id}/check_out\">check out #{@scout.first_name}</a> to undo.".html_safe
    redirect_to @scout
  end


  def check_out
    # @event = Event.current_event
    @scout = Scout.find(params[:id])
    # @scout.update_attribute(:checked_in, false)
    @scout.events.delete(@event)
    flash[:notice] = "#{@scout.full_name} was sucessfully checked out. He will no longer be included in race activities.".html_safe
    redirect_to @scout
  end
end

app/helpers/scouts_helper.rb
module ScoutsHelper
  def check_in?
    @mode == "check_in"
  end
  
  def events_for_scout(scout)
    scout.events.order("start_time DESC").map { |event|
      if event.active
        content_tag :strong, "#{event.name} &laquo; Active".html_safe
      else
        "#{event.name} &raquo; archived"
      end
    }.join("<br />").html_safe
  end
  
  def scout_full_address(scout)
    addr = ""
    addr << (scout.address1 + "<br />") unless scout.address1.blank?
    addr << (scout.address2 + "<br />") unless scout.address2.blank?
    addr << (scout.city + ", " + scout.state + " " + scout.zipcode)
  end
end

app/views/scouts/_check_in_list.html.haml
.text-xlarge
  %table.table.table-hover
    %thead
      %tr
        %th Scout
        %th Den
        %th Rank
        %th Den Leader
        %th Action
    %tbody
      %tr
      - scouts.each do |scout|
        %tr
          %td= link_to scout.full_name, scout_path(scout)
          %td= "Den #{scout.den.try(:den_number)}"
          %td= scout.den.try(:rank)
          %td= scout.den.try(:leader_name)
          - if scout.has_current_event?
            %td= link_to "Remove Check In", check_out_scout_path(scout), class: "btn btn-danger"
          -else
            %td= link_to "Check In", scout_path(scout), class: "btn btn-success"

app/views/scouts/_form.html.haml
= form_for @scout, html: { class: 'form-horizontal' } do |f|
  = render partial: 'layouts/flash_bootstrap', locals: {flash: flash, ar_object: @scout}

  .control-group
    = f.label :den, class: 'control-label'
    .controls
      = f.collection_select :den_id, Den.includes(:pack).sort_den.all, :id, :den_leader_pack, {}, {class: 'span5'}

  .control-group
    = f.label :first_name, class: 'control-label'
    .controls
      = f.text_field :first_name

  .control-group
    = f.label :last_name, class: 'control-label'
    .controls
      = f.text_field :last_name

  .control-group
    = f.label :address1, class: 'control-label'
    .controls
      = f.text_field :address1

  .control-group
    = f.label :address2, class: 'control-label'
    .controls
      = f.text_field :address2

  .control-group
    = f.label :city, 'City, State, Zip', class: 'control-label'
    .controls
      = f.text_field :city, class: 'span3', placeholder: 'city'
      = f.text_field :state, class: 'span1', placeholder: 'state'
      = f.text_field :zipcode, class: 'span2', placeholder: 'zip code'

  .control-group
    = f.label :parent_email1, 'Parent emails', class: 'control-label'
    .controls
      = f.text_field :parent_email1, placeholder: 'primary email'
      = f.text_field :parent_email2, placeholder: 'second email'



  - if @scout.checked_in
    %h3.green #{@scout.first_name} is Checked In!
    %br for #{Event.current_event.try(:name)}
  -else

  .form-actions
    = f.submit class: 'btn btn-primary'
    = link_to 'Cancel', scouts_path, class: 'btn'

app/views/scouts/_heats_list.html.haml
- heat_group = heat.heat_group
- scouts_in_other_heat_groups = heat_group.scouts.all #keep all to avoid n+1 queries
.text-xlarge
  = form_tag heat_add_scout_path(heat.id, 0), html: { class: 'form-horizontal' } do |f|
    %table.table.table-hover
      %thead
        %tr
          %th
          %th Scout
          %th Den
          %th Rank
          %th Den Leader
          %th Action
      %tbody
        %tr
          %td{colspan: 6}
            .pull-right.alert.alert-info.alert-no-margin Check off names and <em>Add Checked to Heat</em> or individual names with <em>Add to Heat</em>
            %button{:type => 'submit', class: 'btn btn-success'}>
              %i.icon-arrow-down
              Add Checked to heat

        - scouts.each do |scout|
          - in_another_heat = scouts_in_other_heat_groups && scouts_in_other_heat_groups.include?(scout)
          %tr{ class: in_another_heat ? 'warning' : '' }
            %td= check_box_tag("scout_ids[]", scout.id) unless in_another_heat
            %td= scout.full_name
            %td= "Den #{scout.den.try(:den_number)}"
            %td= scout.den.try(:rank)
            %td= scout.den.try(:leader_name)
            %td
              - if in_another_heat
                in heats: #{scout.heats_in_event(@event).map(&:name).join(', ')}
              - else
                = link_to "Add to Heat", heat_add_scout_path(heat.id, scout), class: "btn btn-small btn-success"
        %tr
          %td{colspan: 6}
            %button{:type => 'submit', class: 'btn btn-success'}>
              %i.icon-arrow-up
              Add Checked to heat

app/views/scouts/edit.html.haml
.page-header
  %h2 Edit #{@scout.full_name}

.row-fluid
  .span8.offset2
    = render partial: "form"

app/views/scouts/index.html.haml
.row-fluid
  .span12
    .page-header
      .pull-right
        = link_to 'Track Management', track_manager_path, class: "btn"

        = link_to new_scout_path, class: "btn btn-success" do
          %i.icon-plus
          add new scout

      %h2 All Scouts


.row-fluid
  .span12
    %table.table
      %thead
        %tr
          %th Name
          %th Address
          %th Parent Email
          %th Action
      %tbody
        - for scout in @scouts
          %tr
            %td
              %span.xlarge= link_to scout.full_name, edit_scout_path(scout)
            %td= scout_full_address(scout).html_safe
            %td
              #{scout.parent_email1}
              <br />
              #{scout.parent_email2}
            %td
              = link_to 'edit', edit_scout_path(scout), class: 'btn'
              = link_to 'delete', scout, confirm: 'Are you sure? Deleting this scout will also delete all their race results.', method: :delete, class: 'btn btn-danger'

app/views/scouts/index.js.erb
<% if @mode == "heats" %>
	$('#scout-list').html("<%= escape_javascript(render 'heats_list', :scouts => @scouts, :heat => @heat)%>");
  $('input#scout_search').val('');

<% else %>
  $('#scout-list').html("<%= escape_javascript(render 'check_in_list', :scouts => @scouts, :heat_id => @heat_id)%>");

<% end %>

app/views/scouts/new.html.haml
.page-header
  %h2 Add a new Scout

.row-fluid
  .span8.offset2
    = render partial: "form"

app/views/scouts/show.html.haml
/ - title "Scout"
/ - nav_buttons render(partial: 'show_nav_buttons')

.row-fluid
  .span12
    .pull-right
      = link_to check_in_path, class: 'btn btn-success' do
        %i
        Return to Check In

    %h2
      Verify #{@scout.full_name}&rsquo;s information

.row-fluid
  .span10.offset1
    .alert.blink
      %h2.centered Verify the DEN number is correct!

.row-fluid
  .span7.offset1.text-xxlarge
    %table.table-scout-info
      %tr
        %td.span4
          %strong Name:
        %td
          %h2.blue.no-pad= @scout.full_name

      %tr
        %td
          %strong Den:
        %td
          Den #{@scout.den.den_number}, #{@scout.den.rank.pluralize} &ndash; #{@scout.den.pack.name}
          %br
          #{@scout.den.leader_name}, den leader

      %tr
        %td
          %strong Address:
        %td
          = @scout.address1
          - unless @scout.address2.empty?
            %br= @scout.address2
          %br
          #{@scout.city}, #{@scout.state} #{@scout.zipcode}

      %tr
        %td
          %strong Parent Email:
        %td #{@scout.parent_email1}<br />#{@scout.parent_email2}

      %tr
        %td{colspan: "2"}
          - if @scout.has_current_event?
            %h2.green.centered #{@scout.first_name} is checked in for the current race!
          -else
            %h2.red.centered #{@scout.first_name} is not checked in for the current race
      %tr
        %td
      %tr
        %td
          %strong Races:
        %td
          .text-large
            = events_for_scout(@scout)

  .span4
    #scout-picture
      #picture
        = image_tag @scout.picture.url

        = form_for @scout, url: { action: :update }, :html => { multipart: true } do |f|
          = f.file_field :picture
          = f.submit "Upload Picture", class: 'btn'


%h1 &nbsp;
.row-fluid
  .span12.centered
    = link_to "Edit Information", edit_scout_path(@scout), class: "btn btn-large"

    - if current_user.role?(:check_in) || current_user.role?(:track_manager)
      -if @scout.has_current_event?
        = link_to "Check Out #{@scout.first_name} from #{@current_event.name}", check_out_scout_path(@scout), {:confirm => "Are you sure? Checking out a Scout will remove them from the race.", class: "btn btn-large btn-danger"}
      -else
        = link_to "Check In #{@scout.first_name} to #{@current_event.name}", check_in_scout_path(@scout), class: "btn btn-large btn-success"