config/routes.rb
Racearama::Application.routes.draw do

  resources :tracks

  resource :race do
    resources :heat_groups do
      resources :heats do
      end
    end
  end
  match 'heats/:heat_id/remove_scout/:scout_id' => 'heats#remove_scout', :as => 'heat_remove_scout'
  match 'heats/:heat_id/add_scout/:scout_id' => 'heats#add_scout', :as => 'heat_add_scout'

  resources :heats do
    resources :races do
      collection do
        delete 'destroy_races'
      end
    end
    member do
      get 'race'
    end
  end
  resources :races do
    member do
      post "stage"
      post "complete"
      post "run"
    end
  end

  resources :settings

  get 'parent' => 'parent#index'
  get 'track_manager' => 'track_manager#index'
  get 'staging' => 'staging#index'
  get 'check_in' => 'check_in#index'
  get 'check_in/new'
  get "page/welcome"
  get "page/event_not_set"

  resources :scouts do
    member do
      get 'check_in'
      get 'check_out'
    end
  end

  resources :dens
  resources :packs

  resources :events do
    member do
      get "set_active"
    end
  end

  devise_for :users, controllers: { sessions: "users/sessions"}

  get 'track_test' => "track_test#index"
  get 'track_test/gate_up' => "track_test#gate_up"
  get 'track_test/gate_down' => "track_test#gate_down"
  get 'track_test/test_race' => "track_test#test_race"
  get 'track_test/test_lanes' => "track_test#test_lanes"
  put 'track_test/set_current_track' => "track_test#set_current_track"
  get "page/copyright"
  get "page/about"

  root :to => "page#welcome"

end

app/models/heat_group.rb
class HeatGroup < ActiveRecord::Base
  belongs_to :event
  has_many :heats
  attr_accessible :name
  has_many :scouts, through: :heats

  scope :by_name, order("name ASC")
  default_scope order("name ASC")

  validates_presence_of :name
end

app/controllers/heat_groups_controller.rb
class HeatGroupsController < ApplicationController
  # before_filter :current_event
  layout 'layouts/application_bootstrap'

  def index
    @heat_group = HeatGroup.new
    @heat_groups = @event.heat_groups
  end

  # def show
  #   @heat_group = HeatGroup.find(params[:id])
  # end

  # def new
  #   @heat_group = HeatGroup.new
  # end

  def edit
    @heat_group = HeatGroup.find(params[:id])
  end

  def create
    @heat_group = @event.heat_groups.build(params["/race/heat_groups"])

    if @heat_group.save
      redirect_to(race_heat_groups_url, :notice => 'Heat group was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @heat_group = HeatGroup.find(params[:id])

    if @heat_group.update_attributes(params[:heat_group])
      redirect_to(@heat_group, :notice => 'Heat group was successfully updated.')
    else
      redirect_to race_heat_groups_url
    end
  end

  def destroy
    @heat_group = HeatGroup.find(params[:id])
    @heat_group.destroy

    redirect_to race_heat_groups_url
  end
end

app/helpers/heat_groups_helper.rb
module HeatGroupsHelper
end

app/views/heat_groups/_form.html.haml
= form_for @heat_group do |f|
  -if @heat_group.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@heat_group.errors.count, "error")} prohibited this heat_group from being saved:"
      %ul
        - @heat_group.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :event_id
    = f.text_field :event_id
  .actions
    = f.submit 'Save'

app/views/heat_groups/edit.html.haml
%h1 Editing heat_group

= render 'form'

= link_to 'Show', @heat_group
\|
= link_to 'Back', heat_groups_path

app/views/heat_groups/index.html.haml
.row-fluid
  .span12
    .page-header
      .pull-right
        = link_to 'Track Management', track_manager_path, class: "btn"

      %h2 Step 1: Select or Create Heat Group


.row-fluid
  .span10.offset1

    %p.xxlarge You are adding heat groups to the <em>#{@event.name}</em> event.
    %p.xxlarge Heat Groups combine the results of multiple heats so that the winners will be determined for the group. Heat Groups typically run by rank. You will probably want to use 'Tigers', 'Wolves', 'Bears', 'Webelos1', 'Webelos2'.

    %br
    = render 'layouts/event_heat_group'
    %br

    = form_for race_heat_groups_path, html: { class: 'form-horizontal' } do |f|
      = f.label :name, "New Heat Group Name"
      = f.text_field :name
      = f.submit "Add Heat Group", class: 'btn btn-success'
      .help-block Tigers, Wolves, Bears, Webelos1, Webelos2
    %br

    .alert.alert-block.text-xlarge After you add a heat group, add heats for each group.

    %h3 Heat groups in #{@event.name}
    .text-xxlarge
      %table.table.table-bordered
        %thead
          %tr
            %th Name
            %th Scouts
            %th Actions
        %tbody
          - for heat_group in @heat_groups
            %tr
              %td= heat_group.name
              %td #{heat_group.heats.count} heats
              %td
                = link_to "Add Heats to #{heat_group.name}", race_heat_group_heats_path(heat_group.id), class: 'btn btn-primary'
                - if heat_group.heats.count > 0
                  .text-large.help-inline * can't delete heat groups that have heats
                - else
                  = link_to 'Destroy', race_heat_group_path(heat_group), confirm: 'Are you sure?', method: :delete, class: "btn btn-danger"

app/views/heat_groups/new.html.haml
%h1 New heat_group

= render 'form'

= link_to 'Back', heat_groups_path

app/views/heat_groups/show.html.haml
%p
  %b Name:
  = @heat_group.name
%p
  %b Event:
  = @heat_group.event_id

= link_to 'Edit', edit_heat_group_path(@heat_group)
\|
= link_to 'Back', heat_groups_path